version: '3'
services:
  app:
    image: ${REGISTRY_URL}:${COMMIT_ID}
    user: root
    volumes:
      - ${PWD}/tests:/vol/app/tests
      - ${PWD}/src:/vol/app/src
      - ${PWD}/.ci_reports:/vol/app/.ci_reports:z
    privileged: true
    links:
      - postgres-container
    depends_on:
      - postgres-container
    environment:
      - LOG_LEVEL=INFO
      - STAGE=tests
      - DBUS_SESSION_BUS_ADDRESS=/dev/null-

  postgres-container:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 30